import Head from "next/head";
// components
import Header from "@/components/Header";
import MovieList from "@/components/MovieList";
import MovieModal from "@/components/MovieModal";
// styles
import styles from "@/styles/Browse.module.scss";

export const Home = () => {
  return (
    <>
      <Head>
        <title>Internet Flicks</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MovieModal />
      <Header />
      <main className={styles.main}>
        <MovieList category="What's Popular" />
        <MovieList category="Trending" />
        <MovieList category="Upcoming" />
        <MovieList category="Comedy" />
      </main>
    </>
  );
};

export default Home;
