import Head from "next/head";
// components
import Header from "@/components/Header";
import MovieList from "@/components/MovieList";
import MovieModal from "@/components/MovieModal";
// styles
import styles from "@/styles/Browse.module.scss";
// API
import { TMDB_API, API_KEY } from "@/config/index";

export const Home = ({ popularMovies }) => {
  console.log(popularMovies);
  return (
    <>
      <Head>
        <title>Internet Flicks</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MovieModal />
      <Header />
      <main className={styles.main}>
        <MovieList category="What's Popular" movies={popularMovies} />
        <MovieList category="Trending" movies={popularMovies} />
        <MovieList category="Upcoming" movies={popularMovies} />
        <MovieList category="Comedy" movies={popularMovies} />
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const popularRes = await fetch(`${TMDB_API}/movie/popular${API_KEY}`);

  const popularMovies = await popularRes.json();

  return {
    props: {
      popularMovies: popularMovies.results,
    },
  };
};
