import Head from "next/head";
// components
import Header from "@/components/Header";
import MovieList from "@/components/MovieList";
import MovieModal from "@/components/MovieModal";
// styles
import styles from "@/styles/Browse.module.scss";
// API
import { TMDB_API, API_KEY } from "@/config/index";

export const Home = ({
  popularMovies,
  upcomingMovies,
  topRatedMovies,
  nowPlayingMovies,
}) => {
  console.log(popularMovies);
  return (
    <>
      <Head>
        <title>Internet Flicks</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MovieModal />
      <Header />
      <main className={styles.main}>
        <MovieList category="What's Popular" movies={popularMovies} />
        <MovieList category="Top Rated" movies={topRatedMovies} />
        <MovieList category="Upcoming" movies={upcomingMovies} />
        <MovieList category="Now Playing" movies={nowPlayingMovies} />
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const popularRes = await fetch(`${TMDB_API}/movie/popular${API_KEY}`);
  const popularMovies = await popularRes.json();

  const upcomingRes = await fetch(`${TMDB_API}/movie/upcoming${API_KEY}`);
  const upcomingMovies = await upcomingRes.json();

  const topRatedRes = await fetch(`${TMDB_API}/movie/top_rated${API_KEY}`);
  const topRatedMovies = await topRatedRes.json();

  const nowPlayingRes = await fetch(`${TMDB_API}/movie/now_playing${API_KEY}`);
  const nowPlayingMovies = await nowPlayingRes.json();

  return {
    props: {
      popularMovies: popularMovies.results,
      upcomingMovies: upcomingMovies.results,
      topRatedMovies: topRatedMovies.results,
      nowPlayingMovies: nowPlayingMovies.results,
    },
  };
};
