import Head from "next/head";
import Image from "next/image";
// components
import Nav from "../components/Nav";
// styling and animation
import styled from "styled-components";
import { motion } from "framer-motion";

export const Home = () => {
  return (
    <>
      <Head>
        <title>Internet Flicks</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Nav />
        <h1>Internet Flicks</h1>
      </div>
    </>
  );
};

export default Home;
