import Head from "next/head";
// components
import Nav from "../components/Nav";
import Header from "../components/Header";
import MovieList from "../components/MovieList";
// styles
import styles from "@/styles/Home.module.scss";

export const Home = () => {
  return (
    <>
      <Head>
        <title>Internet Flicks</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <Header />
      <main className={styles.main}>
        <MovieList category="What's Popular" />
        <MovieList category="Trending" />
        <MovieList category="Upcoming" />
        <MovieList category="Comedy" />
      </main>
    </>
  );
};
// What's popular
// Trending
// Upcoming
// Genres

export default Home;
