import { useContext, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
// components
import Header from "@/components/Header";
import MovieList from "@/components/MovieList";
import MovieModal from "@/components/MovieModal";
// Context
import Context from "@/context/Context";
// styles
import styles from "@/styles/Browse.module.scss";
// API
import { TMDB_API, API_KEY } from "@/config/index";

export const MovieDetailsPage = ({
  featuredMovie,
  popularMovies,
  topRatedMovies,
  modalMovie,
}) => {
  const router = useRouter();

  const { setModalOpen, setModalData } = useContext(Context);

  useEffect(() => {
    setModalOpen(true);
    setModalData(modalMovie);
  });

  return (
    <>
      <Head>
        <title>Internet Flicks</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MovieModal />
      <Header movie={featuredMovie} />
      <main className={styles.main}>
        <MovieList category="What's Popular" movies={popularMovies} />
        <MovieList category="Top Rated" movies={topRatedMovies} />
      </main>
    </>
  );
};

export default MovieDetailsPage;

export const getServerSideProps = async ({ query }) => {
  const popularRes = await fetch(`${TMDB_API}/movie/popular${API_KEY}`);
  const popularMovies = await popularRes.json();

  const upcomingRes = await fetch(`${TMDB_API}/movie/upcoming${API_KEY}`);
  const upcomingMovies = await upcomingRes.json();

  const topRatedRes = await fetch(`${TMDB_API}/movie/top_rated${API_KEY}`);
  const topRatedMovies = await topRatedRes.json();

  const rng = Math.floor(Math.random() * upcomingMovies.results.length + 1);

  const featuredRes = await fetch(
    `${TMDB_API}/movie/${upcomingMovies.results[rng].id}${API_KEY}`
  );
  const featuredMovie = await featuredRes.json();

  const modalMovieRes = await fetch(`${TMDB_API}/movie/${query.id}${API_KEY}`);
  const modalMovie = await modalMovieRes.json();

  return {
    props: {
      popularMovies: popularMovies.results,
      topRatedMovies: topRatedMovies.results,
      featuredMovie,
      modalMovie,
    },
  };
};
